### ISSUE TITLE
julia installation on gentoo

### ISSUE THREAD

**Issue by wjcunningham7** [eschnett/2018-computational-physics-course#2]
Notes for dev-lang/julia installation on gentoo:
- The prerequisite package sci-libs/spqr fails to compile with an automake error (https://bugs.gentoo.org/586582); unmask version 1.3.1 to solve this
- Only version 0.6.3-r1 of Julia should be used, since the newer versions are not compatible with the current LLVM (https://bugs.gentoo.org/665192); this should be fixed in the next LLVM release at which point Julia version 1.0.0 can be used
- I've compiled and tested julia 0.6.3-r1 on gentoo 4.14.65 and found no obvious errors

**Comment by eschnett** [comment]
The Julia syntax differs between versions 0.6 and 1.0. You should install Julia 1.0; if this doesn't work via the package manager, then I recommend installing it as "Generic Linux Binary".
